language: clojure
lein: lein2
before_install:
  - sudo apt-get install wget -qq
  - sudo apt-get install tar -qq
  - export LIBSVM_VERSION=3.16
  - wget -c http://www.csie.ntu.edu.tw/~cjlin/libsvm/libsvm-$LIBSVM_VERSION.tar.gz
  - tar xvfz libsvm-$LIBSVM_VERSION.tar.gz
  - cd libsvm-$LIBSVM_VERSION
  - make lib all
  - /usr/bin/svm-train
  - svm-train
  - sudo install -D -m755 svm-train /usr/bin/svm-train
  - sudo install -D -m755 svm-predict /usr/bin/svm-predict
  - sudo install -D -m755 svm-scale /usr/bin/svm-scale
  - sudo install -D -m644 java/libsvm.jar /usr/share/java/libsvm.jar
  - sudo install -D -m644 libsvm.so.2 /usr/lib/libsvm.so.2
  - sudo ldconfig
  - cd ..
